### ISSUE TITLE
Problema de responsividade

### ISSUE THREAD

**Issue by guilherssousa** [saulojoab/preview-your-icon#1]
![image](https://github.com/saulojoab/preview-your-icon/assets/47110995/e56c23a8-90a3-45c9-be20-6ff5adef242d)

## Como reproduzir
Aumentar o zoom na página irá reproduzir o problema.

**Comment by saulojoab** [comment]
@guilherssousa brigadão pelo fix! como fiz o projeto rapidão eu subi com a responsividade toda errada mesmo, ia arrumar só depois ahaha 

valeu demais!
